#!/bin/bash

source ./libs/optparse.bash || exit 1
optparse.define short=s long=source desc="Input File or Directory" variable=source_path
# optparse.define short=d long=destination desc="Output File or Directory" variable=destination_path value=False
optparse.define short=f long=format desc="Archive Format eg: tar, tar.gz, iso" variable=format
optparse.define short=e long=extract desc="Extract the contents of the archives in the archive folder" variable=extract value=False
source $( optparse.build )

source ./libs/utils || exit 1
validate_path $source_path

if [ ! -z $extract ]; then
    extract_file $source_path
    pid=$! # Process Id of the previous running command
    spinner $pid
    exit
fi

source ./zkomp.conf || exit 1
if [ ! -z $format ]; then
    compress_with_format $format $source_path
else
    # Default: Tar Gzip (.tar.gz)
    echo "Default: ${default}"
    compress_with_format ${default} $source_path
fi

exit
