#!/bin/bash
source ./zkomp.conf || exit 1

generate_random() {
    # bash generate random 32 character alphanumeric string (upper and lowercase) and 
    NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    # bash generate random 32 character alphanumeric string (lowercase only)
    random_string="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
}

# Validating the file or DIR exists and not repearinf twice or more in the arg
validate_path() {
    if [[ -z "$1" ]]; then
        eval ./zkomp --help
        exit 1
    elif [[ -d $1 ]]; then
        return 0 # 0 = true
    elif [[ -f $1 ]]; then
        return 0 # 0 = true
    else
        echo "$1: No such File or Directory"
        exit 1
    fi
}

# Spinner to show the progress of the process
spinner() {
    spin[0]="-"
    spin[1]="/"
    spin[2]="\\"
    spin[3]="|"
    spin[4]="//"
    echo -n "[processing] ${spin[0]}"
    while kill -0 $pid 2>/dev/null
    do
        for i in "${spin[@]}"
        do
            echo -ne "\b$i"
            sleep 0.09
        done
    done
    echo -ne "\n"
}

extract_file() {
    if [ -f $1 ] ; then
        case $1 in
        *.tar.bz2) tar xjf $1 &;;
        *.tar.gz) tar xzf $1 &;;
        *.bz2) bunzip2 $1 &;; # Compression to be included
        # *.rar) rar x $1 &;;
        *.gz) gunzip $1 &;; # Compression to be included
        *.tar) tar xf $1 &;; 
        *.tbz2) tar xjf $1 &;;
        *.tgz) tar xzf $1 &;;
        *.zip) extract_zip $1 &;;
        *.Z) uncompress $1 &;;
        *.7z) 7z x $1 &;;
        *.iso) extract_iso $1;;
        *) echo "'$1' cannot be extracted via zkomp" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

extract_zip(){
    zip_file=$1
    output_dir=${1%.*}
    generate_random
    exec unzip $1 -d $output_dir | grep $random_string  & # Included grep to run in unzip in silent mode: Just a Hack ;)
}

extract_iso(){
    iso_file=$1
    output_dir=${1%.*}
    generate_random
    exec 7z x $1 -o$output_dir | grep $random_string & # Included grep to run in 7z in silent mode: Just a Hack ;)
}

compress_with_format(){
    
    get_extension $1
    command_name=${conf_name}[command]; command_name=${!command_name}
    options=${conf_name}[options]; options=${!options}
    format=${conf_name}[format]; format=${!format}
    source_path=$2
    generate_random
    # echo "${command_name} ${options} ${source_path}${format} ${source_path} | grep ${random_string} "
    exec $command_name $options $source_path$format $source_path | grep $random_string &
    pid=$! # Process Id of the previous running command
    spinner $pid
}

get_extension() {
    if [ "$1" == "tar" ]; then
        conf_name="tar"
    elif [ "$1" == "tar.gz" ]; then
        conf_name="tar_gz"
    elif [ "$1" == "tar.bz2" ]; then
        conf_name="tar_bz2"
    elif [[ "$1" == "zip" ]]; then
        conf_name="zip"
    # elif [[ '$1' == '' ]]; then
    # elif [[ '$1' == '' ]]; then
    else
        echo "'$1' cannot be compressed via zkomp"
        exit 1
    fi
}